project:
  type: website
  render:
        - index.qmd
        - posts/*
        - The Project/*
        - Sidebar/*    
  
website:
  title: "GSoC - 23 : The MGnify Project"
  
  navbar:
    right:
      # - icon: info-circle-fill
      #   href: /posts/keywords.html
      - icon: globe
        href: https://amartya.vercel.app/
      - icon: github
        href: https://github.com/amartyanambiar
      - icon: linkedin
        href: https://www.linkedin.com/in/amartya-nambiar1/

  sidebar:
    style: "docked"
   
    search: true
    contents:
      - section: "**Highlights**"
        contents:
          - posts/Pathway_Viz/PathwaysExplorer.ipynb
          - posts/Viz_Recon/index.qmd

      - section: "**About**"
        contents:
          - The Project/project.qmd
          - The Project/mentors.qmd
          - The Project/me.qmd

      - Sidebar/keywords.qmd
      - Sidebar/commands.qmd

  favicon: logo.png
format:
  html:
    theme:
            - cosmo
            - styles.scss
    toc: true
    code-overflow: wrap
    # grid:
    #   body-width: 1000px
    #   sidebar-width: 10px
    #   margin-width: 250px
